kubewharf/kelemetry

pkg/audit/consumer/consumer.go
pkg/audit/producer/producer.go

allow different key partitioning strategies for partition-sensitive MQ implementations

feat(audit/producer): customize partition key

---

pkg/frontend/reader/reader.go

After transformation, the trace ID should be changed.

fix(frontend): overwrite TraceID in reference

---

.github/ISSUE_TEMPLATE/bug-report.yaml

chore: remove invalid option in bug-report issue template

---

pkg/frontend/tf/step/collapse_nesting.go

Do not display empty fields as they convey no extra information.

fix(frontend/tf): hide empty fields (especially event.action)

---

.github/workflows/ci.yml
.github/workflows/generate.yml
Dockerfile
go.mod
pkg/aggregator/spancache/local/local.go
pkg/k8s/objectcache/objectcache.go

Upgrade Go version to 1.20
Required for #15

dep: upgrade to Go 1.20

---

pkg/audit/consumer/consumer.go
pkg/audit/message.go
pkg/audit/webhook/webhook.go
pkg/frontend/tf/config/default/default.go

feat: add source IP to audit log tags

---

pkg/aggregator/aggregator.go
pkg/aggregator/eventdecorator/decorator.go
pkg/aggregator/eventdecorator/eventtagger/eventtagger.go
pkg/aggregator/objectdecorator/objecttagger.go
pkg/aggregator/resourcetagger/resource_tagger.go
pkg/imports.go

1. add object decorator to decorate object span tags
2. add audit verbs filter to improve performance

feat(aggregator): split event decorator and object decorator

---

pkg/k8s/objectcache/objectcache.go
pkg/k8s/objectcache/objectcache_test.go

add `cluster` tag to `object_cache_request` metric

feat: add `cluster` tag to `object_cache_request` metric

---

Makefile
pkg/aggregator/aggregator.go
pkg/aggregator/eventdecorator/eventtagger/eventtagger.go
pkg/aggregator/objectspandecorator/decorator.go
pkg/aggregator/objectspandecorator/resourcetagger/objecttagger.go
pkg/imports.go

Refactor object span decorator to allow list pattern, to support smoother option setup
- Fixes #38

fix(object-span-decorator): refactor to list pattern

---

pkg/diff/cache/snapshot_names.go
pkg/diff/controller/controller.go
pkg/diff/decorator/decorator.go
pkg/util/informer/prepush_undelta_store.go

Add creation snapshot to diff decorator
We assume that all add events *after* the initial `Replace` call are incremental.

feat(diff): add creation snapshot

---

pkg/event/controller.go
pkg/frontend/tf/tree/grouping.go

fix: fix nakedret CI lint

---

pkg/k8s/config/interface.go
pkg/kelemetrix/base_quantity_comp.go
pkg/kelemetrix/consumer/consumer.go
pkg/kelemetrix/consumer/consumer_test.go
pkg/kelemetrix/defaults/tags/tags.go

The default `list_timeout` rule does not work because if incorrect implementation of `quantityFilter.test`.

fix: operator = "<" is not tested correctly

---

.github/workflows/ci.yml

Upload coverage data to codecov.io

ci: upload coverage data to codecov

---

.github/workflows/ci.yml
hack/typos.toml
pkg/aggregator/resourcetagger/resource_tagger.go
pkg/metrics/mock.go

Add [typos check](https://github.com/crate-ci/typos) and correct some problems.

chore(ci): add typos check

---

pkg/diff/controller/controller.go

fixed obsolete leftover code from #94

fix(diff/controller): removed unused context

---

Makefile
docs/DEV.md
pkg/aggregator/aggregator.go
pkg/aggregator/eventdecorator/decorator.go
pkg/aggregator/eventdecorator/eventtagger/eventtagger.go
pkg/aggregator/linker/linker.go
pkg/aggregator/objectspandecorator/decorator.go
pkg/aggregator/objectspandecorator/resourcetagger/objecttagger.go
pkg/annotationlinker/linker.go
pkg/audit/consumer/consumer.go
pkg/audit/decorator.go
pkg/diff/decorator/decorator.go
pkg/kelemetrix/registry.go
pkg/manager/interface.go
pkg/ownerlinker/linker.go

- Formalizes decorator pattern into the component manager
- Ensures that list implementations are always initialized and populated to the list before users start initializing.

feat(manager): add ProvideListImpl API

---

pkg/aggregator/aggregator.go
pkg/aggregator/aggregatorevent/event.go
pkg/audit/consumer/consumer.go
pkg/event/controller.go
pkg/util/zconstants/zconstants.go

Remove field pseudospans, see #103 for details.
- Closes #103

feat(aggregator): remove field pseudospans, fixes #103

---

pkg/diff/decorator/decorator.go

Diff is sometimes lost because consumer is slightly lagging behind

fix(diff/decorator): ensure tryOnce is called at least once regardless of fetchEventTimeout

---

docs/DEPLOY.md

Add link to quickstart in DEPLOY.md to recommend using the quick start guide instead of deploying to production right away.

Add link to quickstart in DEPLOY.md

---

charts/kelemetry/templates/_helpers.yaml
charts/kelemetry/templates/consumer.deployment.yaml
charts/kelemetry/values.yaml
pkg/diff/decorator/decorator.go
pkg/manager/interface.go

- Add diff decorator to the default config
- Fixed manager not removing disabled list impls if unindexed
- Closes #127

Fixed #127

---

pkg/frontend/extension/jaeger-storage/storage.go

fix(frontend): typo ccannot -> cannot

---

charts/kelemetry/templates/_helpers.yaml
charts/kelemetry/templates/storage.deployment.yaml

incorrect reference to storage-options-stateless-raw template
fixes #154

fix(chart): incorrect reference to storage-options-stateless-raw template

---

hack/tfconfig.yaml
pkg/frontend/tf/config/file/file.go
pkg/frontend/tf/config/modifier.go
pkg/frontend/tf/defaults/modifier/exclusive.go
pkg/frontend/tf/defaults/modifier/extension.go
pkg/frontend/tf/transform.go

Modifiers with the same class will not be proposed in the same display mode
- Based on #149

feat(frontend): add modifier classes to reduce display mode cardinality

---

pkg/frontend/http/trace/server.go

1. trace extension api can not work because displayMode changed,  fix the display mod
2. get query start and end time from request parameter rather than a fixed half-hour time window

fix(extension): add display mode and time range parameter

---

.golangci.yaml

Fix goheaders license check

---

.github/workflows/build.yml
.github/workflows/ci.yml
.golangci.yaml
Dockerfile
go.mod
go.sum
hack/kind-cluster.yaml
pkg/diff/controller/controller.go
pkg/frontend/backend/interface.go

Fix golangci lint

---

pkg/diff/cmp/cmp.go
pkg/diff/cmp/cmp_test.go
pkg/diff/decorator/decorator.go

Make diff information easier to parse
Includes commits from #299 due to mergeability

Machine readable diff

---

.golangci.yaml
pkg/aggregator/spancache/etcd/etcd.go
pkg/audit/mq/local/local.go
pkg/frontend/reader/merge/merge.go
pkg/frontend/reader/merge/merge_test.go
pkg/frontend/reader/reader.go
pkg/frontend/tf/config/config.go
pkg/frontend/tf/config/file/file.go
pkg/frontend/tf/extension.go
pkg/k8s/k8s.go
pkg/k8s/multileader/elector.go
pkg/manager/interface.go

chore: update .golangci.yaml

---

charts/kelemetry/Chart.yaml
charts/kelemetry/templates/_helpers.yaml
charts/kelemetry/templates/etcd.yaml
charts/kelemetry/templates/scan.deployment.yaml
charts/kelemetry/values.yaml

Fix the chart so it can be used directly
Optimize the chart to use etcd v3.4 and above
Closes #347

Optimize chart

---

.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/docker-build.yml

chore(ci): update ci base image

---

pkg/audit/consumer/consumer.go

Do not produce audit events from specified clusters

feat(consumer): add audit-consumer-exclude-cluster-names option
